config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new'
  get '/articles/name/:name' => 'articles#find_name'
  get '/articles/:id' => 'articles#show', as: 'article_show'
  delete '/articles/:id' => 'articles#delete', as: 'article_delete'
  get '/articles/:id/edit' => 'articles#edit', as: 'article_edit'
  put '/articles/:id' => 'articles#update', as: 'article_update'
  post '/articles' => 'articles#create', as: 'article_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :name, presence: true, uniqueness: true 
  validates :body, presence: true, length: { minimum: 5}  
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index 
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def find_name
    @article = Article.find_by(name: params[:name])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    # @article.name = params[:name] 
    # @article.body = params[:body] 
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit
    end
  end

  def delete
    @article = Article.find(params[:id])
    if @article.destroy
      redirect_to articles_path
     else
      render :index
     end
  end

  private

    def article_params
      params.require(:article).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class = "container">
  <div class = "id_container">
    ID: <%= article.id %>
  </div>

  <div class = "name_container">
    Title: <%= article.name %>
  </div>

  <div class = "body_container">
    Game: <%= article.body %>
  </div>
</div>
<div class = "back">
  <td><%= link_to "Back", articles_path %></td>
</div>

app/views/articles/_form.html.erb
<%= form_with scope: :article, url: article_create_path, locale: true do |f| %>
  <div class = "container">
  
  <div class = "validation_error">
    <% if @article.errors.any? %>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <%end%>
      </ul>
    <%end%>
  </div>
  
  <div class = "form_title">
    <th><%= f.label :Game %></th>
    <th><%= f.text_field :name %></th>
  </div>
  <div class = "form_body">
    <th><%= f.label :Gameplay%></th>
    <th><%= f.text_field :body %></th>
  </div>
  
  <div class = "form_button">
    <%= f.submit :"Add Game" %>
   </div>
  <% end %>
  </div>

app/views/articles/edit.html.erb
<%= form_with scope: :article, url: article_update_path, method: :put, locale: true do |f| %>
<div class = "container">
  <div>
    <% if @article.errors.any? %>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class = "form_title">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class = "form_body">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  
  <div>
    <%= f.submit :'Save Game'%>
  </div>
  <% end %>
</div>

app/views/articles/find_name.html.erb
<%= render @article %>

app/views/articles/index.html.erb
<div class = "banner">
  <h1>The Games I've played</h1>
  <div class = "new_article">
      <%= link_to "Add new Game", articles_new_path %>
  </div>
</div>

<div class="container">
  <div class = "header">
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
    <div>
      <%@articles.each do |article| %>
      <tr class = "label_box">
        <td class = "id_container"><%= article.id %></td>
        <td class = "name_container"><%= article.name %></td>
        <!--<td class = "body_container"><%= article.body %></td>-->
        <div class = "buttons">
        <td class = "button"><%= link_to "Edit", article_edit_path(article.id) %></td>
        <td class = "button"><%= link_to "Delete", article_delete_path(article.id), method: :delete %></td>
        <td class = "button"><%= link_to "Show", article_show_path(article)%></td>
      </div>
      </tr>
      
      <%end%>
    </tbody>
  </table>
  </div>
<div>

app/views/articles/new.html.erb
<%= render"form"%>

app/views/articles/show.html.erb
<%= render @article%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>